"""Protocol constants for the RP2350 relay management group."""

from __future__ import annotations

GROUP_RELAY = 64
PROTOCOL_VERSION = 8
COMMAND_MODEL_VERSION = 2
HARDWARE_NAME = "Waveshare RP2350-Relay-6CH"

RELAY_COUNT = 6
RELAY_MASK = (1 << RELAY_COUNT) - 1
PULSE_MIN_MS = 10
PULSE_MAX_MS = 60000

OP_READ = 0
OP_READ_RSP = 1
OP_WRITE = 2
OP_WRITE_RSP = 3

CMD_IDENTITY = 0x00
CMD_CAPABILITIES = 0x01
CMD_BUILD_INFO = 0x02
CMD_GET = 0x10
CMD_GET_ALL = 0x11
CMD_STATUS = 0x12
CMD_HEALTH = 0x13
CMD_TRANSPORT = 0x14
CMD_SAFETY = 0x15
CMD_WATCHDOG = 0x16
CMD_SET = 0x20
CMD_SET_ALL = 0x21
CMD_PULSE = 0x22
CMD_OFF_ALL = 0x23
CMD_HEARTBEAT = 0x30
CMD_REBOOT = 0x40
CMD_EVENT = 0x7F

ERR_OK = 0
ERR_DECODE = 1
ERR_INVALID_ARGUMENT = 2
ERR_BUSY = 3
ERR_RELAY_IO = 4
ERR_REBOOT_UNAVAILABLE = 5
ERR_REBOOT_FAILED = 6

DEVICE_ERROR_NAMES = {
    ERR_DECODE: "decode",
    ERR_INVALID_ARGUMENT: "invalid_argument",
    ERR_BUSY: "busy",
    ERR_RELAY_IO: "relay_io",
    ERR_REBOOT_UNAVAILABLE: "reboot_unavailable",
    ERR_REBOOT_FAILED: "reboot_failed",
}
